import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Building2, FileText, Home, Plus, Power } from "lucide-react";
import { toast } from "sonner";

const inputClass = "h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-900";

export default function RentEntitiesPanel({ fiscalYearId }: { fiscalYearId: number }) {
  const utils = trpc.useUtils();
  const [buildingId, setBuildingId] = useState<number | null>(null);
  const [unitId, setUnitId] = useState<number | null>(null);
  const [building, setBuilding] = useState({ name: "", code: "", address: "" });
  const [unit, setUnit] = useState({ unitNumber: "", tenantName: "", paymentAccountNumber: "" });
  const [contract, setContract] = useState({ internalContractNumber: "", externalContractNumber: "", tenantName: "", startDate: "", endDate: "" });
  const buildings = trpc.rentEntities.buildings.list.useQuery({ fiscalYearId, includeInactive: true });
  const units = trpc.rentEntities.units.list.useQuery({ fiscalYearId, buildingId: buildingId ?? 0, includeInactive: true }, { enabled: Boolean(buildingId) });
  const contracts = trpc.rentEntities.contracts.list.useQuery({ fiscalYearId, unitId: unitId ?? undefined, includeInactive: true }, { enabled: Boolean(unitId) });
  const invalidate = async () => { await Promise.all([utils.rentEntities.buildings.list.invalidate(), utils.rentEntities.units.list.invalidate(), utils.rentEntities.contracts.list.invalidate()]); };
  const createBuilding = trpc.rentEntities.buildings.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة العمارة."); setBuilding({ name: "", code: "", address: "" }); await invalidate(); }, onError: e => toast.error(e.message) });
  const createUnit = trpc.rentEntities.units.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الوحدة."); setUnit({ unitNumber: "", tenantName: "", paymentAccountNumber: "" }); await invalidate(); }, onError: e => toast.error(e.message) });
  const createContract = trpc.rentEntities.contracts.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة العقد."); setContract({ internalContractNumber: "", externalContractNumber: "", tenantName: "", startDate: "", endDate: "" }); await invalidate(); }, onError: e => toast.error(e.message) });
  const toggleBuilding = trpc.rentEntities.buildings.setActive.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const toggleUnit = trpc.rentEntities.units.setActive.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const toggleContract = trpc.rentEntities.contracts.setActive.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  return <Card className="rounded-2xl border-indigo-100 dark:border-indigo-900/50"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Building2 className="h-4 w-4 text-indigo-600" />البيانات المرجعية المرنة</CardTitle><p className="text-xs text-slate-500">أضف العمارات والوحدات والعقود مرة واحدة، ثم اخترها عند تسجيل كل دفعة. يمكن وجود دفعات متعددة للعقد نفسه.</p></CardHeader><CardContent className="space-y-5">
    <div className="grid gap-4 lg:grid-cols-3">
      <div className="rounded-xl border p-3"><h3 className="mb-2 flex items-center gap-1 font-semibold"><Building2 className="h-4 w-4" />عمارة جديدة</h3><div className="space-y-2"><input className={inputClass} placeholder="اسم العمارة *" value={building.name} onChange={e => setBuilding({ ...building, name: e.target.value })} /><input className={inputClass} placeholder="رمز اختياري" value={building.code} onChange={e => setBuilding({ ...building, code: e.target.value })} /><input className={inputClass} placeholder="العنوان" value={building.address} onChange={e => setBuilding({ ...building, address: e.target.value })} /><Button className="w-full" disabled={!building.name || createBuilding.isPending} onClick={() => createBuilding.mutate({ fiscalYearId, ...building })}><Plus className="h-4 w-4" />إضافة عمارة</Button></div></div>
      <div className="rounded-xl border p-3"><h3 className="mb-2 flex items-center gap-1 font-semibold"><Home className="h-4 w-4" />وحدة جديدة</h3><div className="space-y-2"><select className={inputClass} value={buildingId ?? ""} onChange={e => { setBuildingId(Number(e.target.value) || null); setUnitId(null); }}><option value="">اختر العمارة *</option>{buildings.data?.filter(b => b.isActive).map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select><input className={inputClass} placeholder="رقم الوحدة *" value={unit.unitNumber} onChange={e => setUnit({ ...unit, unitNumber: e.target.value })} /><input className={inputClass} placeholder="اسم المستأجر" value={unit.tenantName} onChange={e => setUnit({ ...unit, tenantName: e.target.value })} /><input className={inputClass} placeholder="رقم الحساب" value={unit.paymentAccountNumber} onChange={e => setUnit({ ...unit, paymentAccountNumber: e.target.value })} /><Button className="w-full" disabled={!buildingId || !unit.unitNumber || createUnit.isPending} onClick={() => createUnit.mutate({ fiscalYearId, buildingId: buildingId!, ...unit })}><Plus className="h-4 w-4" />إضافة وحدة</Button></div></div>
      <div className="rounded-xl border p-3"><h3 className="mb-2 flex items-center gap-1 font-semibold"><FileText className="h-4 w-4" />عقد جديد</h3><div className="space-y-2"><select className={inputClass} value={unitId ?? ""} onChange={e => setUnitId(Number(e.target.value) || null)}><option value="">اختر الوحدة *</option>{units.data?.filter(u => u.isActive).map(u => <option key={u.id} value={u.id}>{u.unitNumber} — {u.tenantName || "دون مستأجر"}</option>)}</select><input className={inputClass} placeholder="رقم العقد الداخلي" value={contract.internalContractNumber} onChange={e => setContract({ ...contract, internalContractNumber: e.target.value })} /><input className={inputClass} placeholder="رقم العقد الخارجي" value={contract.externalContractNumber} onChange={e => setContract({ ...contract, externalContractNumber: e.target.value })} /><input className={inputClass} placeholder="اسم المستأجر" value={contract.tenantName} onChange={e => setContract({ ...contract, tenantName: e.target.value })} /><div className="grid grid-cols-2 gap-2"><input className={inputClass} type="date" aria-label="بداية العقد" value={contract.startDate} onChange={e => setContract({ ...contract, startDate: e.target.value })} /><input className={inputClass} type="date" aria-label="نهاية العقد" value={contract.endDate} onChange={e => setContract({ ...contract, endDate: e.target.value })} /></div><Button className="w-full" disabled={!unitId || createContract.isPending} onClick={() => createContract.mutate({ fiscalYearId, unitId: unitId!, ...contract })}><Plus className="h-4 w-4" />إضافة عقد</Button></div></div>
    </div>
    <div className="grid gap-4 lg:grid-cols-3 text-sm">
      <div><h3 className="mb-2 font-semibold">العمارات ({buildings.data?.length ?? 0})</h3><div className="max-h-40 space-y-1 overflow-auto">{buildings.data?.map(b => <div key={b.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-2 py-1.5 dark:bg-slate-800"><button className="text-right font-medium" onClick={() => { setBuildingId(b.id); setUnitId(null); }}>{b.name}</button><button title={b.isActive ? "تعطيل" : "تفعيل"} onClick={() => toggleBuilding.mutate({ fiscalYearId, id: b.id, isActive: !b.isActive })}><Power className={`h-4 w-4 ${b.isActive ? "text-emerald-600" : "text-slate-400"}`} /></button></div>)}</div></div>
      <div><h3 className="mb-2 font-semibold">الوحدات {buildingId ? `(${units.data?.length ?? 0})` : ""}</h3><div className="max-h-40 space-y-1 overflow-auto">{units.data?.map(u => <div key={u.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-2 py-1.5 dark:bg-slate-800"><button className="text-right" onClick={() => setUnitId(u.id)}>{u.unitNumber} — {u.tenantName || "دون مستأجر"}</button><button title={u.isActive ? "تعطيل" : "تفعيل"} onClick={() => toggleUnit.mutate({ fiscalYearId, id: u.id, isActive: !u.isActive })}><Power className={`h-4 w-4 ${u.isActive ? "text-emerald-600" : "text-slate-400"}`} /></button></div>)}</div></div>
      <div><h3 className="mb-2 font-semibold">العقود {unitId ? `(${contracts.data?.length ?? 0})` : ""}</h3><div className="max-h-40 space-y-1 overflow-auto">{contracts.data?.map(c => <div key={c.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-2 py-1.5 dark:bg-slate-800"><span>{c.internalContractNumber || c.externalContractNumber || `عقد #${c.id}`}</span><button title={c.isActive ? "تعطيل" : "تفعيل"} onClick={() => toggleContract.mutate({ fiscalYearId, id: c.id, isActive: !c.isActive })}><Power className={`h-4 w-4 ${c.isActive ? "text-emerald-600" : "text-slate-400"}`} /></button></div>)}</div></div>
    </div>
  </CardContent></Card>;
}
